site_name: LiteSwarm
site_description: A lightweight framework for building AI agent systems
repo_url: https://github.com/GlyphyAI/liteswarm
repo_name: GlyphyAI/liteswarm

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true
            docstring_style: google
            docstring_section_style: spacy
            merge_init_into_class: true
            separate_signature: true
            show_submodules: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
      toc_depth: 3
      baselevel: 1
      marker: null
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true

nav:
  - Home: index.md
  - API Reference: api.md
  - Advanced Usage: advanced.md
  - Examples: examples.md
